[bookshop-ejs-component-import]
prefix = ["bookshop-ejs-component-import", "ejs-component"]
description = "Creates a quick general ejs component"
category = "Bookshop"
body = """
<%- component("${1:name}", { ${2:props} }); %>
"""
