[jest-suite]
prefix = ["jest-suite", "describe", "jest-describe"]
scope = "javascript"
description = "Creates a quick suite of tests for jest"
category = "Jest"
body = """
describe('${1:suiteName}', () => {
	afterEach(() => {
		jest.clearAllMocks();
	});
	test('${2:testName}', () => {
		
	});
});
"""
