[jest-suite]
prefix = ["jest-suite"]
scope = "javascript"
description = "Creates a quick suite of tests for jest"
category = "Jest"
body = """
describe('${1:suiteName}', () => {
	test('${2:testName}', async () => {
		
	});
});
"""
