[default]
scope = "typescriptreact"
prefix = ["emotion-component"]
description = "Creates a quick emotion component"
body = """
  /** @jsx jsx */
  import { css, jsx } from \"@emotion/core\"
  import React from \"react\"

  /**
   * Interface for ${1:Component} props
   */
  export interface ${1:Component}Props {
    children?: any;
  };

  /**
   *  A ${1:Component} component.
   */
  const ${1:Component}: React.FC<${1:Component}Props> = (props) => {
    return <div css={css``}>${1:Component} component</div>
  }

  export default ${1:Component}
"""

[react]
scope = "typescriptreact"
prefix = ["emotion-component"]
description = "Creates a quick emotion component"
body = """
  /** @jsx jsx */
  import { css, jsx } from \"@emotion/core\"
  import React from \"react\"

  /**
   * Interface for ${1:Component} props
   */
  export interface ${1:Component}Props {
    children?: any;
  };

  /**
   *  A ${1:Component} component.
   */
  const ${1:Component}: React.FC<${1:Component}Props> = (props) => {
    return <div css={css``}>${1:Component} component</div>
  }

  export default ${1:Component}
"""

[url]
scope = ""
prefix = ["url-component"]
description = "URL test"
url = "https://gist.githubusercontent.com/Robbie-Cook/96be95a2c459844e811bcd2208bb053e/raw/a63ba7beea7fafb2b9d5a653cbc901796c7b8fe4/webpack.config.js"